import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const sourcePath = process.argv[2] || 'assets/js/app.js';
const outputPath = process.argv[3] || 'docs/JS_DEPENDENCIES.md';
const source = fs.readFileSync(sourcePath, 'utf8');
new vm.Script(source, { filename: sourcePath });

const lines = source.split(/\r?\n/);
const declarations = [];
const declRe = /^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\b|^(const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(.*)$/;

for (let i = 0; i < lines.length; i += 1) {
  const line = lines[i];
  const match = line.match(declRe);
  if (!match) continue;
  const name = match[1] || match[3];
  const kind = match[1] ? 'function' : match[2];
  const init = match[4] || '';
  declarations.push({ name, kind, line: i + 1, init: init.trim() });
}

for (let i = 0; i < declarations.length; i += 1) {
  const current = declarations[i];
  const next = declarations[i + 1];
  current.endLine = next ? next.line - 1 : lines.length;
  const escaped = current.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const refs = source.match(new RegExp(`\\b${escaped}\\b`, 'g')) || [];
  current.references = Math.max(0, refs.length - 1);

  if (current.kind === 'function') current.role = 'function';
  else if (current.init.startsWith('[')) current.role = 'array/data';
  else if (current.init.startsWith('{')) current.role = 'object/data';
  else if (/=>|function\b/.test(current.init)) current.role = 'function';
  else if (current.kind === 'let' || current.kind === 'var') current.role = 'mutable state';
  else current.role = 'constant/helper';
}

const eventMarkers = [
  ['DOMContentLoaded', /DOMContentLoaded/g],
  ['body click delegation', /document\.body\.addEventListener\(["']click["']/g],
  ['body change delegation', /document\.body\.addEventListener\(["']change["']/g],
  ['body input delegation', /document\.body\.addEventListener\(["']input["']/g],
  ['window error handler', /window\.addEventListener\(["']error["']/g],
];

const markerRows = eventMarkers.map(([label, re]) => {
  const count = (source.match(re) || []).length;
  return { label, count };
}).filter(x => x.count);

const earlyData = declarations.filter(d => d.line <= 1200 && (d.role === 'array/data' || d.role === 'object/data'));
const largeBlocks = declarations
  .map(d => ({ ...d, span: d.endLine - d.line + 1 }))
  .filter(d => d.span >= 80)
  .sort((a, b) => b.span - a.span)
  .slice(0, 20);

const out = [];
out.push('# LegalOS JavaScript dependency inventory');
out.push('');
out.push('Generated by `tools/analyze-app-js.mjs`. This is a **heuristic structural inventory**, not a full AST dependency graph. It is intended to guide low-risk extraction while LegalOS still uses ordered classic scripts.');
out.push('');
out.push('## Snapshot');
out.push('');
out.push(`- Source: \`${sourcePath}\``);
out.push(`- Lines: ${lines.length.toLocaleString('en-US')}`);
out.push(`- Bytes: ${Buffer.byteLength(source, 'utf8').toLocaleString('en-US')}`);
out.push(`- Top-level declarations detected: ${declarations.length}`);
out.push(`- Mutable top-level bindings detected: ${declarations.filter(d => d.kind === 'let' || d.kind === 'var').length}`);
out.push('');
out.push('## Boot / event markers');
out.push('');
if (markerRows.length) {
  out.push('| Marker | Count |');
  out.push('| --- | ---: |');
  for (const row of markerRows) out.push(`| ${row.label} | ${row.count} |`);
} else out.push('_No configured event markers detected._');
out.push('');
out.push('## Large top-level blocks');
out.push('');
out.push('| Name | Kind | Role | Start | Approx. end | Approx. lines | References |');
out.push('| --- | --- | --- | ---: | ---: | ---: | ---: |');
for (const d of largeBlocks) out.push(`| \`${d.name}\` | ${d.kind} | ${d.role} | ${d.line} | ${d.endLine} | ${d.span} | ${d.references} |`);
out.push('');
out.push('## Early data candidates');
out.push('');
out.push('These are top-level array/object declarations in the first 1,200 lines. They are candidates for **ordered classic-script extraction** because moving a declaration to an earlier classic script preserves global lexical visibility to later classic scripts. Each candidate still needs a byte-preserving extraction guard and preview smoke test.');
out.push('');
out.push('| Name | Role | Line | References | Initializer |');
out.push('| --- | --- | ---: | ---: | --- |');
for (const d of earlyData) {
  const init = d.init.slice(0, 72).replaceAll('|', '\\|');
  out.push(`| \`${d.name}\` | ${d.role} | ${d.line} | ${d.references} | \`${init}${d.init.length > 72 ? '…' : ''}\` |`);
}
out.push('');
out.push('## Full top-level declaration inventory');
out.push('');
out.push('| # | Name | Kind | Role | Line | Approx. span | References |');
out.push('| ---: | --- | --- | --- | ---: | ---: | ---: |');
for (let i = 0; i < declarations.length; i += 1) {
  const d = declarations[i];
  out.push(`| ${i + 1} | \`${d.name}\` | ${d.kind} | ${d.role} | ${d.line} | ${d.endLine - d.line + 1} | ${d.references} |`);
}
out.push('');
out.push('## Stage 2b extraction rules');
out.push('');
out.push('1. Keep classic `<script>` execution order while dependencies remain implicit.');
out.push('2. Move only complete top-level declarations; do not rewrite legal text/data during structural extraction.');
out.push('3. For each move, verify the extracted declaration bytes match the original bytes and that the remainder of `app.js` is unchanged except for the removed declaration.');
out.push('4. Load extracted files before `assets/js/app.js`, then run `tools/check-html.mjs` and Netlify deploy preview.');
out.push('5. Convert to ES modules only after cross-file dependencies and mutable state are explicit.');
out.push('');

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, out.join('\n') + '\n', 'utf8');
console.log(`Wrote ${outputPath}`);
console.log(`  ${declarations.length} top-level declaration(s)`);
console.log(`  ${largeBlocks.length} large block(s)`);
console.log(`  ${earlyData.length} early data candidate(s)`);
