import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const indexPath = process.argv[2] || 'index.html';
const outputPath = process.argv[3] || 'docs/JS_DEPENDENCIES.md';
const html = fs.readFileSync(indexPath, 'utf8');
const baseDir = path.dirname(path.resolve(indexPath));
const scriptRefs = [...html.matchAll(/<script\b[^>]*\bsrc=["']([^"']+)["'][^>]*><\/script>/gi)]
  .map(m => m[1])
  .filter(src => src.startsWith('assets/js/'));

if (!scriptRefs.length) throw new Error('No local JavaScript modules found in index.html.');

const declRe = /^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\b|^(const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(.*)$/;
const modules = [];

for (const ref of scriptRefs) {
  const file = path.resolve(baseDir, ref);
  const source = fs.readFileSync(file, 'utf8');
  new vm.Script(source, { filename: ref });
  const lines = source.split(/\r?\n/);
  const declarations = [];
  for (let i = 0; i < lines.length; i += 1) {
    const match = lines[i].match(declRe);
    if (!match) continue;
    const name = match[1] || match[3];
    const kind = match[1] ? 'function' : match[2];
    const init = match[4] || '';
    declarations.push({ name, kind, line: i + 1, init: init.trim() });
  }
  modules.push({
    ref,
    source,
    lines: lines.length,
    bytes: Buffer.byteLength(source, 'utf8'),
    declarations,
    mutable: declarations.filter(d => d.kind === 'let' || d.kind === 'var').length,
    events: {
      domReady: (source.match(/DOMContentLoaded/g) || []).length,
      bodyClick: (source.match(/document\.body\.addEventListener\(["']click["']/g) || []).length,
      documentClick: (source.match(/document\.addEventListener\(["']click["']/g) || []).length,
      windowError: (source.match(/window\.addEventListener\(["']error["']/g) || []).length
    }
  });
}

const owners = new Map();
for (const mod of modules) {
  for (const decl of mod.declarations) {
    if (!owners.has(decl.name)) owners.set(decl.name, []);
    owners.get(decl.name).push(mod.ref);
  }
}

for (const mod of modules) {
  const own = new Set(mod.declarations.map(d => d.name));
  const deps = new Map();
  for (const [name, defs] of owners) {
    if (own.has(name) || name.length < 3) continue;
    const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    if (!new RegExp(`\\b${escaped}\\b`).test(mod.source)) continue;
    for (const def of defs) {
      if (def === mod.ref) continue;
      deps.set(def, (deps.get(def) || 0) + 1);
    }
  }
  mod.dependencies = [...deps.entries()].sort((a, b) => b[1] - a[1]);
}

const out = [];
out.push('# LegalOS JavaScript dependency inventory');
out.push('');
out.push('Generated by `tools/analyze-app-js.mjs` from the script order in `index.html`. This is a **heuristic structural inventory**, not a full AST dependency graph. It is intended to protect the ordered classic-script model used by V14.');
out.push('');
out.push('## Snapshot');
out.push('');
out.push(`- Entry document: \`${indexPath}\``);
out.push(`- Ordered JavaScript modules: ${modules.length}`);
out.push(`- Total JavaScript bytes: ${modules.reduce((n, m) => n + m.bytes, 0).toLocaleString('en-US')}`);
out.push(`- Total JavaScript lines: ${modules.reduce((n, m) => n + m.lines, 0).toLocaleString('en-US')}`);
out.push(`- Top-level declarations detected: ${modules.reduce((n, m) => n + m.declarations.length, 0)}`);
out.push(`- Mutable top-level bindings detected: ${modules.reduce((n, m) => n + m.mutable, 0)}`);
out.push('');
out.push('## Ordered module map');
out.push('');
out.push('| # | Module | Bytes | Lines | Top-level declarations | Mutable bindings | Heuristic upstream dependencies |');
out.push('| ---: | --- | ---: | ---: | ---: | ---: | --- |');
modules.forEach((m, i) => {
  const deps = m.dependencies.slice(0, 6).map(([ref, count]) => `\`${path.basename(ref)}\` (${count})`).join(', ') || '—';
  out.push(`| ${i + 1} | \`${m.ref}\` | ${m.bytes.toLocaleString('en-US')} | ${m.lines.toLocaleString('en-US')} | ${m.declarations.length} | ${m.mutable} | ${deps} |`);
});
out.push('');
out.push('## Boot / event markers');
out.push('');
out.push('| Module | DOMContentLoaded | body click delegation | document click listener | window error handler |');
out.push('| --- | ---: | ---: | ---: | ---: |');
for (const m of modules.filter(m => Object.values(m.events).some(Boolean))) {
  out.push(`| \`${m.ref}\` | ${m.events.domReady} | ${m.events.bodyClick} | ${m.events.documentClick} | ${m.events.windowError} |`);
}
out.push('');
out.push('## Module-owned top-level declarations');
out.push('');
for (const m of modules) {
  out.push(`### \`${m.ref}\``);
  out.push('');
  if (!m.declarations.length) {
    out.push('_No declarations detected by the line-oriented heuristic._');
  } else {
    const names = m.declarations.map(d => `\`${d.name}\`${d.kind === 'let' || d.kind === 'var' ? ' *(mutable)*' : ''}`);
    out.push(names.join(', '));
  }
  out.push('');
}
out.push('## Interpretation rules');
out.push('');
out.push('1. Script order is part of the V14 runtime contract because modules are still classic scripts sharing the global lexical environment.');
out.push('2. A heuristic dependency means a module references a name declared by another module; common words and dynamic property access can create false positives or omissions.');
out.push('3. Do not reorder scripts solely from this inventory. Use `tools/check-v14-structure.mjs`, CI and browser smoke tests together.');
out.push('4. Legal-content accuracy is outside this inventory; structural refactoring must not silently rewrite legal data.');
out.push('5. ES-module conversion should be a separate migration after browser behavior is stable and explicit imports/exports can replace implicit globals.');
out.push('');

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, out.join('\n') + '\n', 'utf8');
console.log(`Wrote ${outputPath}`);
console.log(`  ${modules.length} module(s)`);
console.log(`  ${modules.reduce((n, m) => n + m.declarations.length, 0)} declaration(s)`);
